version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    ports:
      - "8443:8080"
    container_name: mocks
    volumes:
      - ./test/mocks:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]

  db:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./test/db:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    container_name: dynamodb-local

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=iam,s3,sqs,sns
      - AWS_DEFAULT_REGION=sa-east-1
      - EDGE_PORT=4566
    ports:
      - '4566-4597:4566-4597'
