version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    ports:
      - "8443:8080"
    container_name: mocks
    volumes:
      - ./internal/test/mocks:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]

  db:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./internal/test/db:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    container_name: dynamodb-local
