// Code generated by mockery v2.51.1. DO NOT EDIT.

package _mocks

import (
	context "context"

	entity "github.com/hernangonzalez1987/scriptBreakdown/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockScriptBreakdownUseCase is an autogenerated mock type for the ScriptBreakdownUseCase type
type MockScriptBreakdownUseCase struct {
	mock.Mock
}

type MockScriptBreakdownUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScriptBreakdownUseCase) EXPECT() *MockScriptBreakdownUseCase_Expecter {
	return &MockScriptBreakdownUseCase_Expecter{mock: &_m.Mock}
}

// ScriptBreakdown provides a mock function with given fields: ctx, breakdownRequest
func (_m *MockScriptBreakdownUseCase) ScriptBreakdown(ctx context.Context, breakdownRequest entity.ScriptBreakdownRequest) (*entity.ScriptBreakdownResult, error) {
	ret := _m.Called(ctx, breakdownRequest)

	if len(ret) == 0 {
		panic("no return value specified for ScriptBreakdown")
	}

	var r0 *entity.ScriptBreakdownResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ScriptBreakdownRequest) (*entity.ScriptBreakdownResult, error)); ok {
		return rf(ctx, breakdownRequest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ScriptBreakdownRequest) *entity.ScriptBreakdownResult); ok {
		r0 = rf(ctx, breakdownRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ScriptBreakdownResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ScriptBreakdownRequest) error); ok {
		r1 = rf(ctx, breakdownRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScriptBreakdownUseCase_ScriptBreakdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScriptBreakdown'
type MockScriptBreakdownUseCase_ScriptBreakdown_Call struct {
	*mock.Call
}

// ScriptBreakdown is a helper method to define mock.On call
//   - ctx context.Context
//   - breakdownRequest entity.ScriptBreakdownRequest
func (_e *MockScriptBreakdownUseCase_Expecter) ScriptBreakdown(ctx interface{}, breakdownRequest interface{}) *MockScriptBreakdownUseCase_ScriptBreakdown_Call {
	return &MockScriptBreakdownUseCase_ScriptBreakdown_Call{Call: _e.mock.On("ScriptBreakdown", ctx, breakdownRequest)}
}

func (_c *MockScriptBreakdownUseCase_ScriptBreakdown_Call) Run(run func(ctx context.Context, breakdownRequest entity.ScriptBreakdownRequest)) *MockScriptBreakdownUseCase_ScriptBreakdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ScriptBreakdownRequest))
	})
	return _c
}

func (_c *MockScriptBreakdownUseCase_ScriptBreakdown_Call) Return(_a0 *entity.ScriptBreakdownResult, _a1 error) *MockScriptBreakdownUseCase_ScriptBreakdown_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScriptBreakdownUseCase_ScriptBreakdown_Call) RunAndReturn(run func(context.Context, entity.ScriptBreakdownRequest) (*entity.ScriptBreakdownResult, error)) *MockScriptBreakdownUseCase_ScriptBreakdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScriptBreakdownUseCase creates a new instance of MockScriptBreakdownUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScriptBreakdownUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScriptBreakdownUseCase {
	mock := &MockScriptBreakdownUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
